---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kim-postgres
  labels:
    kim.rbac/aggregate-to-kim-developer: "true"
rules:
  - apiGroups:
    - postgresql.cnpg.io
    resources:
    - imagecatalogs
    verbs:
    - get
    - list
    - watch
---
apiVersion: kim.karolinska.se/v1
kind: ModifyClusterRole
metadata:
  name: my-edit
spec:
  clusterRole: edit
  removeRules:
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - create
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
